# Generated by Django 5.2.16 on 2026-08-01 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('reference_number', models.CharField(blank=True, help_text='e.g. LACD/HR/VAC/2026/02', max_length=100)),
                ('department', models.CharField(help_text='e.g. Engineering & Infrastructure', max_length=150)),
                ('location', models.CharField(default='Monrovia HQ (with county travel)', max_length=150)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-Time'), ('contract', 'Contractual'), ('consultancy', 'Consultancy'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('description', models.TextField(help_text='Key responsibilities & role summary')),
                ('requirements', models.TextField(help_text='Qualifications, experience & skills required')),
                ('application_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(default='hr@lacd.gov.lr', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Career Vacancy',
                'verbose_name_plural': 'Career Vacancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('author', models.CharField(default='LACD Communications Team', max_length=100)),
                ('category', models.CharField(choices=[('press_release', 'Press Release'), ('announcement', 'Agency Announcement'), ('field_update', 'Field Progress Update'), ('event', 'Official Event')], default='press_release', max_length=30)),
                ('excerpt', models.TextField(help_text='Short abstract for news feeds', max_length=400)),
                ('content', models.TextField(help_text='Full news article content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_featured', models.BooleanField(default=False)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News & Update',
                'verbose_name_plural': 'News & Updates',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('reference_number', models.CharField(help_text='e.g. LACD/RFQ/2026/004', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('rfq', 'Request for Quotation (RFQ)'), ('rfp', 'Request for Proposal (RFP)'), ('eoi', 'Expression of Interest (EOI)'), ('ncb', 'National Competitive Bidding')], default='rfq', max_length=20)),
                ('description', models.TextField(help_text='Scope of work and tender requirements summary')),
                ('tender_document', models.FileField(help_text='PDF document upload', upload_to='tenders/')),
                ('opening_date', models.DateField()),
                ('closing_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open for Submission'), ('under_evaluation', 'Under Evaluation'), ('awarded', 'Awarded'), ('closed', 'Closed')], default='open', max_length=20)),
                ('contact_email', models.EmailField(default='procurement@lacd.gov.lr', max_length=254)),
                ('submission_location', models.CharField(default='LACD HQ Procurement Office, Capitol Hill, Monrovia', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Procurement Opportunity',
                'verbose_name_plural': 'Procurement Opportunities',
                'ordering': ['-opening_date'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('icon_class', models.CharField(default='ri-community-line', help_text='Remix/FontAwesome icon class name e.g. ri-road-ster-line', max_length=100)),
                ('short_description', models.TextField(help_text='Brief snippet for cards', max_length=500)),
                ('description', models.TextField(help_text='Detailed program description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], default='active', max_length=20)),
                ('county', models.CharField(choices=[('bomi', 'Bomi'), ('bong', 'Bong'), ('gbarpolu', 'Gbarpolu'), ('grand_bassa', 'Grand Bassa'), ('grand_cape_mount', 'Grand Cape Mount'), ('grand_gedeh', 'Grand Gedeh'), ('grand_kru', 'Grand Kru'), ('lofa', 'Lofa'), ('margibi', 'Margibi'), ('maryland', 'Maryland'), ('montserrado', 'Montserrado'), ('nimba', 'Nimba'), ('river_cess', 'River Cess'), ('river_gee', 'River Gee'), ('sinoe', 'Sinoe'), ('national', 'Nationwide / Multiple Counties')], default='national', max_length=50)),
                ('budget', models.CharField(blank=True, help_text='e.g. $2,500,000 USD', max_length=100, null=True)),
                ('target_beneficiaries', models.CharField(blank=True, help_text='e.g. 50,000 Farmers & Youth', max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Development Program',
                'verbose_name_plural': 'Development Programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('annual_report', 'Annual Report'), ('strategic_plan', 'Strategic Plan'), ('policy_document', 'Policy & Framework'), ('procurement_report', 'Procurement & Financial Audit'), ('research', 'Research & Case Study')], default='annual_report', max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('pdf_file', models.FileField(help_text='Upload PDF document', upload_to='publications/pdf/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='publications/covers/')),
                ('file_size', models.CharField(blank=True, help_text='e.g. 4.2 MB', max_length=50)),
                ('publication_date', models.DateField()),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publication & Report',
                'verbose_name_plural': 'Publications & Reports',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('beneficiary_name', models.CharField(help_text='Community name, farmer group or individual', max_length=150)),
                ('county', models.CharField(choices=[('bomi', 'Bomi'), ('bong', 'Bong'), ('gbarpolu', 'Gbarpolu'), ('grand_bassa', 'Grand Bassa'), ('grand_cape_mount', 'Grand Cape Mount'), ('grand_gedeh', 'Grand Gedeh'), ('grand_kru', 'Grand Kru'), ('lofa', 'Lofa'), ('margibi', 'Margibi'), ('maryland', 'Maryland'), ('montserrado', 'Montserrado'), ('nimba', 'Nimba'), ('river_cess', 'River Cess'), ('river_gee', 'River Gee'), ('sinoe', 'Sinoe'), ('national', 'Nationwide / Multiple Counties')], default='bong', max_length=50)),
                ('quote', models.TextField(help_text='Key quote from beneficiary', max_length=300)),
                ('content', models.TextField(help_text='Detailed story background and impact')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Success Story',
                'verbose_name_plural': 'Success Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_description', models.TextField(max_length=500)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('ongoing', 'Ongoing / In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='ongoing', max_length=20)),
                ('county', models.CharField(choices=[('bomi', 'Bomi'), ('bong', 'Bong'), ('gbarpolu', 'Gbarpolu'), ('grand_bassa', 'Grand Bassa'), ('grand_cape_mount', 'Grand Cape Mount'), ('grand_gedeh', 'Grand Gedeh'), ('grand_kru', 'Grand Kru'), ('lofa', 'Lofa'), ('margibi', 'Margibi'), ('maryland', 'Maryland'), ('montserrado', 'Montserrado'), ('nimba', 'Nimba'), ('river_cess', 'River Cess'), ('river_gee', 'River Gee'), ('sinoe', 'Sinoe'), ('national', 'Nationwide / Multiple Counties')], default='montserrado', max_length=50)),
                ('location_details', models.CharField(blank=True, help_text='District, town or community name', max_length=255)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='0 to 100 percent')),
                ('budget', models.CharField(blank=True, help_text='Allocated budget e.g. $450,000 USD', max_length=100)),
                ('contractor', models.CharField(blank=True, help_text='Lead contractor or execution agency', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.program')),
            ],
            options={
                'verbose_name': 'County Project',
                'verbose_name_plural': 'County Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
