# Generated by Django 5.2.16 on 2026-08-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_heroslide_sitesetting_navigationmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='contact_email',
            field=models.EmailField(default='hr@padev.org', max_length=254),
        ),
        migrations.AlterField(
            model_name='career',
            name='reference_number',
            field=models.CharField(blank=True, help_text='e.g. PADEV/HR/VAC/2026/02', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='author',
            field=models.CharField(default='PADEV Communications Team', max_length=100),
        ),
        migrations.AlterField(
            model_name='procurementopportunity',
            name='contact_email',
            field=models.EmailField(default='procurement@padev.org', max_length=254),
        ),
        migrations.AlterField(
            model_name='procurementopportunity',
            name='reference_number',
            field=models.CharField(help_text='e.g. PADEV/RFQ/2026/004', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='procurementopportunity',
            name='submission_location',
            field=models.CharField(default='PADEV HQ Procurement Office, Sophie Community, Congo Town, Monrovia', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(default='Sophie Community, Opposite HILA School, Congo Town, Monrovia, Liberia', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='agency_acronym',
            field=models.CharField(default='PADEV', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(default='info@padev.org', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(default='+231 088 651 8396', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='Partners in Development (PADEV)', max_length=255),
        ),
    ]
