# Generated by Django 5.2.16 on 2026-08-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_career_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(help_text='e.g. Team Leader, Deputy Team Leader, Cofounder', max_length=200)),
                ('role_category', models.CharField(choices=[('management', 'Management Team'), ('founder', 'Founders & Board'), ('board', 'Board of Directors')], default='management', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short biography shown in the team popup')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['role_category', 'order', 'full_name'],
            },
        ),
    ]
