# Generated by Django 5.2.16 on 2026-08-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organization name e.g. USAID', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('website', models.URLField(blank=True, help_text='Optional official website link')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client / Partner',
                'verbose_name_plural': 'Clients & Partners',
                'ordering': ['order', 'name'],
            },
        ),
    ]
