# Generated by Django 5.2.16 on 2026-09-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Optional background image for the hero section on the homepage', null=True, upload_to='site/'),
        ),
    ]
