# Generated by Django 5.2.16 on 2026-09-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesetting_hero_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='newsupdate',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='procurementopportunity',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='program',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='publication',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='successstory',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160),
        ),
    ]
