# Generated by Django 5.2.16 on 2026-09-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_career_meta_description_newsupdate_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Card heading e.g. Community Forest Governance', max_length=200)),
                ('description', models.TextField(help_text='Short copy shown under the heading', max_length=300)),
                ('icon_class', models.CharField(default='ri-leaf-line', help_text='Remix icon class name e.g. ri-tree-line', max_length=100)),
                ('theme', models.CharField(choices=[('green', 'Green'), ('gold', 'Gold'), ('navy', 'Navy'), ('rose', 'Rose')], default='green', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Program Structure Card',
                'verbose_name_plural': 'Program Structure',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
