# Generated by Django 5.2.16 on 2026-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_read_more_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='program_structure_heading',
            field=models.CharField(default='Program Structure', help_text='Heading shown above the Program Structure cards on the homepage', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='program_structure_intro',
            field=models.TextField(blank=True, default='Driven by specialized expertise, Partners in Development delivers impactful solutions across four core areas: Forest Governance, Livelihood & Enterprise Development, Strategic Communication, and Stakeholder Engagement.', help_text='Introduction shown under the heading on the homepage. Leave blank to hide it.'),
        ),
    ]
