# Generated by Django 5.2.16 on 2026-09-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesetting_program_structure_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_text',
            field=models.TextField(default="Start Your Community's\n**Beautiful & Bright** Future.", help_text='Homepage headline. Start a new line for a line break; wrap words in ** to show them in the gold gradient. Leave blank to hide the headline.'),
        ),
    ]
