# Generated by Django 5.2.16 on 2026-09-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesetting_hero_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='donor',
            field=models.CharField(blank=True, help_text='Funding organisation e.g. GEF, USAID, Sweden Embassy', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='implementing_agency',
            field=models.CharField(blank=True, help_text='Lead sector or executing agency e.g. Forestry Development Authority (FDA)', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='partners',
            field=models.TextField(blank=True, help_text='Partner organisations, one per line'),
        ),
        migrations.AddField(
            model_name='project',
            name='report_link',
            field=models.URLField(blank=True, help_text='Public link to the project report or factsheet', max_length=500),
        ),
    ]
