# Generated by Django 5.2.16 on 2026-09-27 18:07

from django.db import migrations, models


def point_about_anchor_at_about_page(apps, schema_editor):
    """Send the 'About Us' menu item to the new /about/ page.

    The menu used to jump to the About section on the homepage (/#about).
    Now that the page exists, an existing menu row follows it there; a row an
    editor has already pointed somewhere else is left alone.
    """
    NavigationMenu = apps.get_model('core', 'NavigationMenu')
    for url in ('/#about', '/#about/', '#about'):
        NavigationMenu.objects.filter(url=url).update(url='/about/')


def restore_homepage_anchor(apps, schema_editor):
    NavigationMenu = apps.get_model('core', 'NavigationMenu')
    NavigationMenu.objects.filter(url='/about/').update(url='/#about')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesetting_about_content_sitesetting_about_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_intro',
            field=models.CharField(default='A registered, accredited and recognized Liberian organization contributing to national development through community-based natural resource management.', help_text='One-line summary under the About Us page title', max_length=300),
        ),
        migrations.RunPython(point_about_anchor_at_about_page, restore_homepage_anchor),
    ]
