# Generated by Django 5.2.16 on 2026-09-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_default_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_mission',
            field=models.TextField(default='Empowering communities and building strong alliances to:\n- Address environmental challenges;\n- Sustainably manage natural resources;\n- Drive systemic change; and\n- Protect our shared future.', help_text='Mission, shown on the About Us page. Blank line = new paragraph, a line starting with - is a bullet, and words wrapped in ** are bold.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_values',
            field=models.TextField(default='Environmental Stewardship\nTransparency\nMutual Accountability\nInclusiveness and participation\nShared tolerance and diversity', help_text='Core values shown as chips on the About Us page — one value per line (a leading - is allowed and ignored).'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_vision',
            field=models.TextField(default='PADEV aspires to:\n- Be the leader of community-led natural resource management;\n- Drive sustainable national development; and\n- Contribute to global environmental goals.', help_text='Vision, shown on the About Us page. Blank line = new paragraph, a line starting with - is a bullet, and words wrapped in ** are bold.'),
        ),
    ]
