# Generated by Django 5.2.16 on 2026-09-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_sitesetting_about_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='home_about_badge',
            field=models.CharField(blank=True, default='ABOUT US', help_text='Label above the homepage About heading. Leave blank to hide it.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_about_badge_label',
            field=models.CharField(blank=True, default='Community-Based Development', help_text='Small caption under the badge text.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_about_badge_year',
            field=models.CharField(blank=True, default='Since 2016', help_text='Large text in the gold badge over the photos, e.g. Since 2016. Leave blank to hide the badge.', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_about_heading',
            field=models.CharField(blank=True, default='Building Alliances to Mitigate Global Environmental Challenges.', help_text='Heading of the homepage About section. Leave blank to hide it.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_about_highlight_1_text',
            field=models.CharField(blank=True, default='Community forest governance & protected area support.', help_text='Text of the first highlight box.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_about_highlight_1_title',
            field=models.CharField(blank=True, default='Conservation & Governance', help_text="Title of the first highlight box. Leave both boxes' fields blank to hide a box.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_about_highlight_2_text',
            field=models.CharField(blank=True, default='Conservation agriculture, beekeeping & social inclusion.', help_text='Text of the second highlight box.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_about_highlight_2_title',
            field=models.CharField(blank=True, default='Livelihoods & Inclusion', help_text="Title of the second highlight box. Leave both boxes' fields blank to hide a box.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_about_image_1',
            field=models.ImageField(blank=True, help_text='Left photo of the homepage About collage. Portrait or square photo works best. Until one is uploaded, a placeholder photo is shown.', upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_about_image_2',
            field=models.ImageField(blank=True, help_text='Right photo of the homepage About collage. Until one is uploaded, a placeholder photo is shown.', upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_about_text',
            field=models.TextField(blank=True, default='Founded in August 2016, Partners in Development (PADEV) is a leading national institution that builds its intervention on the collective competence of its diverse professionals — delivering community-based natural resource management, forest conservation, and livelihood development across over 100 forest-fringed communities in Liberia.', help_text='Introduction paragraph of the homepage About section. Blank line = new paragraph, and words wrapped in ** are bold. Leave blank to hide it.'),
        ),
    ]
