# Generated by Django 5.2.16 on 2026-09-27 20:16

from django.db import migrations, models

OLD_DEFAULT = "Start Your Community's\n**Beautiful & Bright** Future."

NEW_DEFAULT = (
    "Empowering Communities. **Preserving Nature.** Securing Futures.\n\n"
    "The Future of **Sustainable Forest Management** Belongs to Communities…\n\n"
    "We partner with local communities to **sustainably manage their natural resources**, "
    "protecting biodiversity while building resilient local economies.\n\n"
    "Putting **A Human Face** to Community Forestry…\n\n"
    "We empower forest dependent communities to protect their forests, build **sustainable "
    "livelihoods**, and fight climate change from bottom, up.\n\n"
    "**Meet the Communities** and Support Our Mission\n\n"
    "Reaching **100+ Rural Communities**, leaving real impacts\n\n"
    "**Building infrastructure** with the people\n\n"
    "**Laying foundations** for growth\n\n"
    "**Building capacity** and leaving lasting legacy"
)


def set_rotating_headlines(apps, schema_editor):
    """Swap in the client's rotating headlines — but only where they were never edited.

    A record still holding the original default headline gets the new set; a
    record an editor has written themselves is left exactly as it is.
    """
    SiteSetting = apps.get_model('core', 'SiteSetting')
    SiteSetting.objects.filter(hero_text=OLD_DEFAULT).update(hero_text=NEW_DEFAULT)


def restore_original_headline(apps, schema_editor):
    SiteSetting = apps.get_model('core', 'SiteSetting')
    SiteSetting.objects.filter(hero_text=NEW_DEFAULT).update(hero_text=OLD_DEFAULT)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sitesetting_home_about_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_text',
            field=models.TextField(blank=True, default='Empowering Communities. **Preserving Nature.** Securing Futures.\n\nThe Future of **Sustainable Forest Management** Belongs to Communities…\n\nWe partner with local communities to **sustainably manage their natural resources**, protecting biodiversity while building resilient local economies.\n\nPutting **A Human Face** to Community Forestry…\n\nWe empower forest dependent communities to protect their forests, build **sustainable livelihoods**, and fight climate change from bottom, up.\n\n**Meet the Communities** and Support Our Mission\n\nReaching **100+ Rural Communities**, leaving real impacts\n\n**Building infrastructure** with the people\n\n**Laying foundations** for growth\n\n**Building capacity** and leaving lasting legacy', help_text='Homepage headlines, shown one after another with a slow fade. Separate headlines with a blank line — there is no limit. Start a new line inside a headline for a line break, and wrap words in ** to show them in the gold gradient. Leave blank to hide the headline.'),
        ),
        migrations.RunPython(set_rotating_headlines, restore_original_headline),
    ]
