# Generated by Django 5.2.16 on 2026-10-01 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_swap_old_hero_headlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='programs/gallery/')),
                ('caption', models.TextField(blank=True, help_text='Caption shown under the photo on the programme detail page. Leave blank for no caption.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.program')),
            ],
            options={
                'verbose_name': 'Programme Photo',
                'verbose_name_plural': 'Programme Photos',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
