# Generated by Django 5.2.16 on 2026-10-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_programimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/')),
                ('caption', models.TextField(blank=True, help_text='Caption shown under the photo on the article page. Leave blank for no caption.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.newsupdate')),
            ],
            options={
                'verbose_name': 'News Photo',
                'verbose_name_plural': 'News Photos',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
