# Generated by Django 5.2.16 on 2026-10-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_newsimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsupdate',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name': 'News & Article', 'verbose_name_plural': 'News & Articles'},
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='category',
            field=models.CharField(choices=[('press_release', 'Articles'), ('announcement', 'Agency Announcement'), ('field_update', 'Field Progress Update'), ('event', 'Official Event')], default='press_release', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.TextField(blank=True, help_text='Caption shown under the photo on the project detail page. Leave blank for no caption.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Photo',
                'verbose_name_plural': 'Project Photos',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
