"""
Django settings for lacd_project project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import urllib.parse

import dj_database_url
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-local-development-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if host.strip()]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.redirects',
    'hitcount',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
]

ROOT_URLCONF = 'lacd_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'core.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'lacd_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ['DATABASE_URL'],
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Monrovia'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary is enabled only when production credentials are configured.
_cloudinary_url = os.environ.get('CLOUDINARY_URL', '')
if _cloudinary_url and not os.environ.get('CLOUDINARY_CLOUD_NAME'):
    _parsed_cloudinary_url = urllib.parse.urlparse(_cloudinary_url)
    os.environ.setdefault('CLOUDINARY_CLOUD_NAME', _parsed_cloudinary_url.hostname or '')
    os.environ.setdefault('CLOUDINARY_API_KEY', _parsed_cloudinary_url.username or '')
    os.environ.setdefault('CLOUDINARY_API_SECRET', _parsed_cloudinary_url.password or '')

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
}

STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

if _cloudinary_url or all(CLOUDINARY_STORAGE.values()):
    INSTALLED_APPS = ['cloudinary', 'cloudinary_storage'] + INSTALLED_APPS
    STORAGES['default'] = {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    }
else:
    STORAGES['default'] = {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1


UNFOLD = {
    "SITE_HEADER": _("PADEV Admin Portal"),
    "SITE_TITLE": _("PADEV CMS"),
    "SITE_URL": "/",
    "SITE_SYMBOL": "public",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "lacd_project.settings.environment_callback",
    "STYLES": [],
    "SCRIPTS": [],
    "COLORS": {
        "primary": {
            "50": "240 249 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56 189 248",
            "500": "14 165 233",
            "600": "2 132 199",
            "700": "3 105 161",
            "800": "7 89 133",
            "900": "12 74 110",
            "950": "8 47 73",
        },
        "secondary": {
            "50": "249 250 251",
            "100": "243 244 246",
            "200": "229 231 235",
            "300": "212 214 217",
            "400": "163 170 180",
            "500": "113 128 150",
            "600": "71 85 105",
            "700": "51 65 85",
            "800": "30 41 59",
            "900": "15 23 42",
            "950": "8 13 28",
        },
        "success": {
            "50": "240 253 244",
            "100": "220 252 231",
            "200": "187 247 208",
            "300": "134 239 172",
            "400": "74 222 128",
            "500": "34 197 94",
            "600": "22 163 74",
            "700": "21 128 61",
            "800": "22 101 52",
            "900": "20 83 45",
            "950": "15 54 33",
        },
        "info": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
        "warning": {
            "50": "255 247 237",
            "100": "255 237 213",
            "200": "254 215 170",
            "300": "253 186 116",
            "400": "251 146 60",
            "500": "249 115 22",
            "600": "234 88 12",
            "700": "194 65 12",
            "800": "154 52 18",
            "900": "124 45 18",
            "950": "76 29 15",
        },
        "danger": {
            "50": "255 241 242",
            "100": "255 228 230",
            "200": "254 205 211",
            "300": "251 150 166",
            "400": "244 63 94",
            "500": "239 68 68",
            "600": "220 38 38",
            "700": "185 28 28",
            "800": "153 27 27",
            "900": "127 29 29",
            "950": "69 13 15",
        },
        "rose": {
            "50": "255 241 242",
            "100": "255 228 230",
            "200": "254 205 211",
            "300": "251 150 166",
            "400": "244 63 94",
            "500": "225 29 72",
            "600": "219 39 119",
            "700": "190 24 93",
            "800": "157 23 77",
            "900": "131 24 67",
            "950": "83 17 58",
        },
        "indigo": {
            "50": "238 242 255",
            "100": "224 231 255",
            "200": "199 210 254",
            "300": "165 180 252",
            "400": "129 140 248",
            "500": "99 102 241",
            "600": "79 70 229",
            "700": "67 56 202",
            "800": "55 48 163",
            "900": "49 46 129",
            "950": "30 27 87",
        },
        "orange": {
            "50": "255 247 237",
            "100": "255 237 213",
            "200": "254 215 170",
            "300": "253 186 116",
            "400": "251 146 60",
            "500": "249 115 22",
            "600": "234 88 12",
            "700": "194 65 12",
            "800": "154 52 18",
            "900": "124 45 18",
            "950": "76 29 15",
        },
        "gray": {
            "50": "249 250 251",
            "100": "243 244 246",
            "200": "229 231 235",
            "300": "212 214 217",
            "400": "163 170 180",
            "500": "113 128 150",
            "600": "71 85 105",
            "700": "51 65 85",
            "800": "30 41 59",
            "900": "15 23 42",
            "950": "8 13 28",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("CMS & Site"),
                "separator": True,
                "items": [
                    {
                        "title": _("Site Settings"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:core_sitesetting_changelist"),
                    },
                    {
                        "title": _("Navigation Menus"),
                        "icon": "menu",
                        "link": reverse_lazy("admin:core_navigationmenu_changelist"),
                    },
                    {
                        "title": _("Hero Slides"),
                        "icon": "slideshow",
                        "link": reverse_lazy("admin:core_heroslide_changelist"),
                    },
                ],
            },
            {
                "title": _("Programs & Projects"),
                "separator": True,
                "items": [
                    {
                        "title": _("Programs"),
                        "icon": "category",
                        "link": reverse_lazy("admin:core_program_changelist"),
                    },
                    {
                        "title": _("Projects"),
                        "icon": "engineering",
                        "link": reverse_lazy("admin:core_project_changelist"),
                    },
                ],
            },
            {
                "title": _("Content"),
                "separator": True,
                "items": [
                    {
                        "title": _("News & Updates"),
                        "icon": "newspaper",
                        "link": reverse_lazy("admin:core_newsupdate_changelist"),
                    },
                    {
                        "title": _("Success Stories"),
                        "icon": "auto_stories",
                        "link": reverse_lazy("admin:core_successstory_changelist"),
                    },
                    {
                        "title": _("Publications"),
                        "icon": "description",
                        "link": reverse_lazy("admin:core_publication_changelist"),
                    },
                ],
            },
            {
                "title": _("Operations"),
                "separator": True,
                "items": [
                    {
                        "title": _("Procurement"),
                        "icon": "gavel",
                        "link": reverse_lazy("admin:core_procurementopportunity_changelist"),
                        "badge": "lacd_project.settings.procurement_badge_callback",
                    },
                    {
                        "title": _("Careers"),
                        "icon": "work",
                        "link": reverse_lazy("admin:core_career_changelist"),
                    },
                    {
                        "title": _("Contact Submissions"),
                        "icon": "mail",
                        "link": reverse_lazy("admin:core_contactsubmission_changelist"),
                        "badge": "lacd_project.settings.unread_contacts_badge_callback",
                    },
                ],
            },
            {
                "title": _("Administration"),
                "separator": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}


def environment_callback(request):
    """Show environment badge in admin header."""
    return _("Development")


def procurement_badge_callback(request):
    """Show count of open procurement opportunities."""
    from core.models import ProcurementOpportunity
    count = ProcurementOpportunity.objects.filter(status='open').count()
    return str(count) if count else None


def unread_contacts_badge_callback(request):
    """Show count of unread contact submissions."""
    from core.models import ContactSubmission
    count = ContactSubmission.objects.filter(is_read=False).count()
    return str(count) if count else None
